version: '3.8'
services:
  dev:
    hostname: vahala
    image: kungfury:1.0
    init: true
    volumes:
      - type: bind
        source: ~/.ssh
        target: /home/qm/.ssh
      - type: bind
        source: ~/.gitconfig
        target: /home/qm/.gitconfig
      - type: bind
        source: ~/
        target: /home/qm/workspace
      - type: bind
        source: ~/bin
        target: /home/qm/hostbin
      - type: bind
        source: /local/mnt/workspace
        target: /local/mnt/workspace
      - type: volume
        source: home
        target: /home/qm/
    tty: true
    stdin_open: true

volumes:
  home:
