services:
  dev:
    hostname: vahala
    image: bundle:latest
    init: true
    volumes:
      - type: bind
        source: ~/.ssh
        target: /home/qm/.ssh
      - type: bind
        source: ~/.gitconfig
        target: /home/qm/.gitconfig
      - type: bind
        source: /local/mnt/workspace
        target: /local/mnt/workspace
      - type: volume
        source: home
        target: /home/qm/
    tty: true
    stdin_open: true

volumes:
  home:
